// <auto-generated />
using System;
using Company.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Company.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    partial class CompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Company.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityRefRefId")
                        .IsRequired()
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryRefRefId")
                        .IsRequired()
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DistrictRefRefId")
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LastModifiedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityRefRefId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryRefRefId");

                    b.HasIndex("DistrictRefRefId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Company.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("EmployeesCount")
                        .HasColumnType("smallint");

                    b.Property<short>("EstablishedYear")
                        .HasColumnType("smallint");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("LastModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SectorRefId")
                        .IsRequired()
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SectorRefId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyFollower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyFollower");
                });

            modelBuilder.Entity("Company.Domain.Refs.CityRef", b =>
                {
                    b.Property<string>("RefId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RefId");

                    b.ToTable("CityRef", "LK");
                });

            modelBuilder.Entity("Company.Domain.Refs.CountryRef", b =>
                {
                    b.Property<string>("RefId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RefId");

                    b.ToTable("CountryRef", "LK");
                });

            modelBuilder.Entity("Company.Domain.Refs.DistrictRef", b =>
                {
                    b.Property<string>("RefId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RefId");

                    b.ToTable("DistrictRef", "LK");
                });

            modelBuilder.Entity("Company.Domain.Refs.SectorRef", b =>
                {
                    b.Property<string>("RefId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RefId");

                    b.ToTable("SectorRef", "LK");
                });

            modelBuilder.Entity("Company.Domain.Entities.Address", b =>
                {
                    b.HasOne("Company.Domain.Refs.CityRef", "CityRef")
                        .WithMany()
                        .HasForeignKey("CityRefRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Domain.Entities.Company", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Domain.Refs.CountryRef", "CountryRef")
                        .WithMany()
                        .HasForeignKey("CountryRefRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Domain.Refs.DistrictRef", "DistrictRef")
                        .WithMany()
                        .HasForeignKey("DistrictRefRefId");

                    b.Navigation("CityRef");

                    b.Navigation("CountryRef");

                    b.Navigation("DistrictRef");
                });

            modelBuilder.Entity("Company.Domain.Entities.Company", b =>
                {
                    b.HasOne("Company.Domain.Refs.SectorRef", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Company.Domain.ValueObjects.TaxInfo", "TaxInfo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TaxCountryId")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("TaxCountryId");

                            b1.Property<string>("TaxNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("TaxNumber");

                            b1.Property<string>("TaxOffice")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("TaxOffice");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Sector");

                    b.Navigation("TaxInfo");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyFollower", b =>
                {
                    b.HasOne("Company.Domain.Entities.Company", "Company")
                        .WithMany("Followers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company.Domain.Entities.Company", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Followers");
                });
#pragma warning restore 612, 618
        }
    }
}
